create database  EVALUACION_HITO3;
use EVALUACION_HITO3;

/*PREGUNTA 2*/
CREATE OR REPLACE FUNCTION COMPARAR_CADENA(A VARCHAR(20), B VARCHAR(20))
RETURNS VARCHAR(40)
BEGIN
    DECLARE RESPUESTA VARCHAR(40) DEFAULT '';
    IF STRCMP(A,B)=0 THEN SET RESPUESTA='SON IGUALES';
        ELSE  SET RESPUESTA='NO SON IGUALES';
        END IF;
    RETURN RESPUESTA;
end;

SELECT COMPARAR_CADENA('LUIS','LUIS');


/*PREGUNTA 4*/

CREATE OR REPLACE FUNCTION  SERIE_DE_FIBONANCI(TOPE INTEGER)
RETURNS TEXT
BEGIN
    DECLARE A INTEGER DEFAULT 0;
    DECLARE B INTEGER DEFAULT 1;
    DECLARE AUXILIAR INTEGER DEFAULT 0;
    DECLARE CADENA TEXT DEFAULT '';
    SET CADENA=CONCAT(A,',',B,',');

IF TOPE=1 THEN SET CADENA='0';
ELSEIF TOPE=2 THEN SET CADENA='0,1';
ELSEIF TOPE<=0 THEN SET CADENA='TIENE QUE SER MAYOR A CERO';
ELSE
    REPEAT
    SET AUXILIAR=A+B;
    SET CADENA=CONCAT(CADENA,AUXILIAR,',');
    SET A=B;
    SET B=AUXILIAR;
    until AUXILIAR>=TOPE-2 end repeat;
END IF;
    RETURN CADENA;
END;

SELECT SERIE_DE_FIBONANCI(7);

/*PREGUNTA 5*/

CREATE OR REPLACE FUNCTION  VOLTEAR_CADENA(PALABRA TEXT)
RETURNS TEXT
BEGIN
    DECLARE RESPUESTA TEXT DEFAULT '';
    SET RESPUESTA= REVERSE(PALABRA);
    RETURN PALABRA;
end;
SELECT VOLTEAR_CADENA('GENIAL');
